### ISSUE TITLE
Image Thumbnail Size on Mobile

### ISSUE THREAD

**Issue by Deagan** [hnhx/librex#100]
An adjustment to the image size on mobile, displaying a "gallery view", similar to Google, Brave, Startpage, etc?

The current view is a single column, but I think two/three columns would look great!

![image](https://user-images.githubusercontent.com/19179570/202134468-40f9d628-1b41-4aaa-aeab-be5e097be225.jpeg)

![image](https://user-images.githubusercontent.com/19179570/202134496-142a01b5-b100-4f06-847c-2d07871c6a1c.jpeg)

**Comment by hnhx** [comment]
Personal preference, I like the way it is now.
