### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in /www/wwwroot/librex/engines/bittorrent/thepiratebay.php on line 11

### ISSUE THREAD

**Issue by Metastem** [hnhx/librex#102]
Warning: Invalid argument supplied for foreach() in /www/wwwroot/librex/engines/bittorrent/thepiratebay.php on line 11
![QQ截图20221125122007](https://user-images.githubusercontent.com/110768529/203900525-6870042c-3d89-41e3-a29f-280c817c4c56.png)

**Comment by hnhx** [comment]
Should be fixed now.
