### ISSUE TITLE
HTML Injection Vulnerability

### ISSUE THREAD

**Issue by ssddanbrown** [hnhx/librex#105]
Hello :wave: 

I noticed a XSS vulnerability within a file.
Don't want to create a public PR or point to the issue in public without permission, how would you prefer me to communicate the issue?

---

On a tangential note, I came across this project after encountering this [reddit thread](https://www.reddit.com/r/opensource/comments/z44jut/midori_browser_now_with_its_own_search_engine/). [This thread also relevant](https://www.reddit.com/r/selfhosted/comments/zaidyj/another_sh_search_engine/).

In the first thread the poster states: 

> We are working together with LibreX to improve and make this browser an alternative and strong solution before seax, searxng, Google etc, this is beta 1 but we will be working on many more changes.

Is that correct? From my perspective they seem to have taken your project, [tweaked it](https://gitlab.com/astiango/astian-search/-/commits/main), added their own donation links, and hosted it without providing any attribution back to the original contributors. Just wanted to give them the benefit of doubt before assuming they are lying but, as per my comments in those threads, there's a lot of red flags in my opinion.

**Comment by hnhx** [comment]
Hey!
Send an email to hnhx@danwin1210.de about the vulnerability.

> We are working together with LibreX to improve and make this browser an alternative and strong solution before seax, searxng, Google etc, this is beta 1 but we will be working on many more changes.

No, they just forked my project, I have never been asked about anything so "working with" is a lie.
Also they removed my donation options and it looks like they haven't even added anything yet to the project lol

**Comment by hnhx** [comment]
In fact it seems like they just removed things lol
Currency conversion or wikipedia results are not working.
Try: "2.4 xmr to usd" or "openbsd"

**Comment by hnhx** [comment]
What a joke

**Comment by ssddanbrown** [comment]
Thanks, have just sent an email.

> No, they just forked my project, I have never been asked about anything so "working with" is a lie.

Ah, suspected as much, what a shame; Thanks for confirming.

**Comment by hnhx** [comment]
I have checked the email, I will fix the issue in the next commit, thanks.

**Comment by hnhx** [comment]
Fixed in the latest commit.
