### ISSUE TITLE
Error processing url wikipedia locale

### ISSUE THREAD

**Issue by rhp7rholype** [hnhx/librex#107]
Hello.
I think there's a mistake in processing the Wikipedia url.
If you need to find information, like in Greek, we get the right results. And for example, there's a result on the wikipedia, if we try to get on the wikipedia page, we're being redirected to the main page in the Wikipedia.
Looking for the reason, I realized that there was a mistake in replacing the url.
Wikipedia's shaped the url of the format: %lang%.%url%... you're gonna need to add it to the end of the results: ?lang=%lang%
Thank you

**Comment by rhp7rholype** [comment]
I reading source code...
Need add check in file main/engines/google/text.php, method get_text_results, 
before 115 line: "$url = check_for_privacy_frontend($url);"
add maybe pseudo code: 
if ($special_search == 7) { //wikipedia
  $tmp = split($url, '.');
  $pos_wiki = find_str($tmp, "wikipedia");
  if ($pos_wiki > 0) {
    $lang = $tmp[$pos_wiki - 1];//because $lang.wikipedia.org/...
    $url .= "?lang=".$lang;
   }
}
I not understand, how work git

**Comment by hnhx** [comment]
Fixed it, thanks
