### ISSUE TITLE
[Feature request] location-based searches?

### ISSUE THREAD

**Issue by Impeta** [hnhx/librex#108]
Title says it all. Is this feasible within your front-end? As in, make searches and find them based on selected country regions/languages while not requiring Javascript? If not, feel free to disregard it. Whoogle has got me covered in that anyway. :+1:

**Comment by hnhx** [comment]
The host can change the language already via config.php, I will implement this feature in the user settings too.

**Comment by hnhx** [comment]
Thanks

**Comment by hnhx** [comment]
Next commit the feature should be available

**Comment by dm1tz** [comment]
Sorry to bother, but you probably forgot to push it :p @hnhx
