### ISSUE TITLE
Frontend Support: Fandom to Breezewiki

### ISSUE THREAD

**Issue by trueauracoral** [hnhx/librex#114]
https://bw.vern.cc/ (The official instance, https://breezewiki.com isn't working)

>BreezeWiki makes wiki pages on Fandom readable
>It removes ads, videos, and suggested content, leaving you with a clean page that doesn't slow down your device or use up your data.
>BreezeWiki can also be called an "alternative frontend for Fandom".
>To use BreezeWiki, just replace "fandom.com" with "bw.vern.cc", and you'll instantly be teleported to a better world.

Redirecting is **NOT** like advertised when using an the other instances that aren't official.

This is how it actually works for articles:
`"https://" + BREEZEWIKI_INSTANCE + "/" + subdomain + path`

**Comment by hnhx** [comment]
Added it, thanks for the suggestion.
