### ISSUE TITLE
Why not Images search does not display

### ISSUE THREAD

**Issue by garywu520** [hnhx/librex#117]
Thanks!

![1](https://user-images.githubusercontent.com/26731482/209799370-8baad08d-1ef8-48ee-bad2-395858acd288.jpg)

**Comment by hnhx** [comment]
It works fine now, maybe it was a temporary issue.

**Comment by Greatz08** [comment]
same issue i am facing unable to see any images but can see images in public instances , i thought it might be related to https so i used reverse proxy on my domain but still not image
