### ISSUE TITLE
[Question] How to enable tor and i2p for my LibreX instance because in the config I think tor is set as enabled, but the listings show it as disabled.

### ISSUE THREAD

**Issue by Kame03** [hnhx/librex#118]
![Screenshot_2022-12-28_23-14-14](https://user-images.githubusercontent.com/98698826/209873500-18bd4469-16ee-425f-b5ca-48ff2eec845e.png)
you can see here it's set to false so it's not disabled and on listing it shows as disabled.
![Screenshot_2022-12-28_23-14-44](https://user-images.githubusercontent.com/98698826/209873549-8bfc48ba-5d8d-465a-93da-94f4ec878e89.png)
Is there anything else that has to be done in order for it to be enabled?

when it comes to i2p I don't know much about it, what has to be done regarding that?

I'm sorry for wasting your time, I really like your project, keep up good work!

**Comment by hnhx** [comment]
The disabling hidden services config part refers to disabling search results for the tor section in librex.
If you want to host a tor hidden service follow this guide: https://community.torproject.org/onion-services/setup/

**Comment by Kame03** [comment]
I use Caddy web server, but I will try to do this, if i succeed I will write back to you, thank you for informing me, and thank you for your time.
