### ISSUE TITLE
[New frontend request] Frontend for Medium

### ISSUE THREAD

**Issue by cheese-potatoes** [hnhx/librex#137]
There are two front ends.
One is Scribe ([source code](https://sr.ht/~edwardloveall/Scribe)) ([official instance](https://scribe.rip/)) and the other is LibMedium ([source code](https://github.com/realaravinth/libmedium)) ([official instance](https://libmedium.batsense.net)).

The differences I know are
- Scribe has more history.
- LibMedium proxies images, Scribe does not.
- LibMedium supports docker.

Here are example pages:
- https://scribe.rip/@ftrain/big-data-small-effort-b62607a43a8c
- https://libmedium.batsense.net/@ftrain/big-data-small-effort-b62607a43a8c

Thanks for the great work!

**Comment by OshekharO** [comment]
I already created pr #135

**Comment by hnhx** [comment]
That PR will be merged once the issue I mentioned will be solved.
