### ISSUE TITLE
Trying to install a test version on my localhost?

### ISSUE THREAD

**Issue by findborg** [hnhx/librex#153]
I am trying to install a test version on my localhost in the directory of http://localhost/sapi   
the pages load but I am getting all kinds of errors and it will not perform a search.
Is there something I need to do with the config.php file?

1. Warning: file_get_contents(.git/refs/heads/main): failed to open stream: No such file or directory in C:\wamp\www\sapi\misc\footer.php on line 10    error from homepage
2.  Notice: Trying to access array offset on value of type null in C:\wamp\www\sapi\engines\special\wikipedia.php on line 8   error from results page....  one of many and no results showing.

**Comment by hnhx** [comment]
What distro and what version of php are you using?

**Comment by findborg** [comment]
wamp  server for localhost
php version 7.4.26
I downloaded the file zip so,  I am guessing the latest...

**Comment by hnhx** [comment]
Ye sorry I don't use Windows I'm not sure how to help.
