### ISSUE TITLE
Multiple search languages

### ISSUE THREAD

**Issue by Sir-Photch** [hnhx/librex#158]
I like how librex anonymizes my search queries.

I have a problem though: very often, my search queries are in different languages. And if my query does not match the language that I specified in the settings, the search results get worse.

Would it be possible to add a feature that allows users to set multiple languages as their search language? Like a comma-seperated array: `en, de`.

**Comment by hnhx** [comment]
Google doesn't really support this feature so I'm sorry I can't add it.
