### ISSUE TITLE
CONFIG_GOOGLE_LANGUAGUE shall be splitted

### ISSUE THREAD

**Issue by jkumeboshi** [hnhx/librex#163]
the `CONFIG_GOOGLE_LANGUAGUE` option (and also his counterpart in web page settings) shall be splitted in 2.

PLEASE NOTE: there is a typo, should be **CONFIG_GOOGLE_LANGUAGE**

as far as I know, following query strings means:

`hl=$language`
Tell google that I'm speaking $language (independently from the google top level domain I'm using)

`lr=lang_$language`
Tells google to shows ONLY results that he recognize to be written in specified $language

So if I set `$language=fr`, LibreX shows me results only in French language.

If I put an empty string in $language, results are not what I expect, so by now as workaround I 'm using an invalid lang id `none` and a national TLD.

So my proposal is to have following settings:

French TLD, French web site language, ONLY French results
```
CONFIG_GOOGLE_DOMAIN=fr
CONFIG_GOOGLE_LANGUAGE_SITE=fr
CONFIG_GOOGLE_LANGUAGE_RESULTS=fr
```

main TLD, French web site language, result's lang unspecified
```
CONFIG_GOOGLE_DOMAIN=com
CONFIG_GOOGLE_LANGUAGE_SITE=fr
CONFIG_GOOGLE_LANGUAGE_RESULTS=
```

... and so on

**Comment by juniorbotelho** [comment]
Whoa, that's a big oopsie! Thanks for pointing it out, I'll definitely fix that up later this week. Your suggestions are greatly appreciated!

**Comment by juniorbotelho** [comment]
I have submitted a pull request that fixes the typo issue as you requested. Now let's talk about your suggestions, do you want to make a PR or do you prefer to discuss the matter until the project contributors implement them based on the discussion?

**Comment by jkumeboshi** [comment]
I'm trying to implement the changes, although PHP is not one of my primary languages, so please be patient :)

**Comment by hnhx** [comment]
I have added it in this commit: https://github.com/hnhx/librex/commit/a8645b7eb616480fc5fcfc8d454caa7fd648895d

**Comment by hnhx** [comment]
@jkumeboshi  so dont bother working on it
