### ISSUE TITLE
Wikipedia Result Language Support

### ISSUE THREAD

**Issue by beucismis** [hnhx/librex#168]
Fetch based on Google result language for Wikipedia containers appearing in search results support.

![](https://user-images.githubusercontent.com/40023234/219898753-4991ac74-22c7-4754-bfb1-73faab88773c.png)

**Comment by juniorbotelho** [comment]
I just created a PR for your issue. If the repository maintainer accepts the changes, I will build the image for the Docker Hub and then you will be able to use it with support for other languages in Wikipedia search results.

**Comment by beucismis** [comment]
Great job. Thanks.

**Comment by hnhx** [comment]
Merged it, however this only allows the host to set the wikipedia language so far.
I will make it so the user can set it as well in the next commit.
