### ISSUE TITLE
[Feature Request] Add keyboard shortcuts to navigate easier.

### ISSUE THREAD

**Issue by Quantenzitrone** [hnhx/librex#171]
### Description
I think some Keyboard Shortcuts would greatly improve the user experience.
Specifically, i would like to have the DuckDuckGo Keyboard Shortcuts:
<blockquote>
<p><strong>Open results:</strong></p>

<ul>
    <li>
        Enter or l or o — go to the highlighted result, or use it right away to go
        to the first result
    </li>
    <li>Ctrl/Cmd+Enter — open a result in the background</li>
    <li>d — domain search (if a result is highlighted)</li>
    <li>
        ' or v — open the highlighted result in a new window/tab. Since this uses
        JavaScript, you need to turn off pop-up blockers first.
    </li>
</ul>
<p><strong>Move around:</strong></p>

<ul>
    <li>
        ← and → — navigate Instant Answer tabs. When an Instant Answer is open,
        navigate within the Instant Answer.
    </li>
    <li>↓ or j — next search result</li>
    <li>↑ or k — previous search result</li>
    <li>/ or h — go to search box</li>
    <li>s — go to misspelling link (if any)</li>
    <li>t — go to top</li>
    <li>m — go to main results</li>
</ul>
</blockquote>

copied from: https://help.duckduckgo.com/duckduckgo-help-pages/features/keyboard-shortcuts/

It doesn't have to be exact that, but ←, →, ↓, ↑, Enter and something to return to the search box would be great.

Also, I don't know if this is even possible without JavaScript.
Keyboard shortcuts in general seem to be: https://www.amitmerchant.com/html-only-keyboard-shortcuts/

### Alternatives
Using Web Extensions like Vim emulators or Key Jump.

**Comment by juniorbotelho** [comment]
I think we can use JavaScript in a way that respects users' freedom, like Richard Stallman suggests. But I'm not sure if the repo maintainer agrees with that. 🤔

**Comment by hnhx** [comment]
I have tried the HTML only method on Firefox but it doesnt really seem to work.

**Comment by hnhx** [comment]
@juniorbotelho No JS is allowed in the codebase sorry.

**Comment by juniorbotelho** [comment]
Ok! I already know haha

**Comment by hnhx** [comment]
I will close this but lmk if anyone finds a HTML only solution that works with modern browsers.
