### ISSUE TITLE
Remove Bibliogram for good

### ISSUE THREAD

**Issue by NoaHimesaka1873** [hnhx/librex#193]
Bibliogram has been discontinued for a while due to IG backend changes and does not work anymore. Removing it would be sensible decision.

**Comment by codedipper** [comment]
Working on it. :)

Here's a full list of all the files where it contained Bibliogram code (hope I didn't miss any):
- config.example.php
- docker/attributes.sh
- docker/php/config.php
- docker/php/php.dockerfile
- misc/tools.php

**Comment by codedipper** [comment]
Solved in #198

**Comment by codedipper** [comment]
Solved in #199 (for real this time)
