### ISSUE TITLE
add lx.tfwno.life instance

### ISSUE THREAD

**Issue by tfwnolife** [hnhx/librex#196]
Please add [my instance](https://lx.tfwno.life) to the list.
Tor: http://542i54lcucx57kilxjpsqn4r4prtwpxpk3ktrilepsscmy6p5ma6mnqd.onion

**Comment by hnhx** [comment]
Your general results doesnt seem to work

**Comment by tfwnolife** [comment]
As I've said on discord, sometimes it works, sometimes it doesn't. Right now it seems to work again.
Idk what causes this and how to fix it.

**Comment by SkMyPP** [comment]
> Your general results doesnt seem to work

This seems to be an issue with LibreX itself, not this instance. I've tried searching with most public instances and get no results, even with the official instance at search.femboy.hu
