### ISSUE TITLE
Is the addition of instance librex.yogeshlamichhane.com.np feasible?

### ISSUE THREAD

**Issue by whoisYoges** [hnhx/librex#200]
I used to host [librex.yogeshlamichhane.com.np](https://librex.yogeshlamichhane.com.np) with a free hosting provider, but it was removed from your list of instances and I'm not sure why. However, I have now upgraded/changed my hosting plan and I was wondering if it's possible to add the instance back?

**Comment by hnhx** [comment]
Your instance probably got removed because it was offline at some point.

I can add it back yeah, just make a PR and I will merge it

**Comment by hnhx** [comment]
Okay I added it myself, no need to make a PR.
