### ISSUE TITLE
Add search.spaceint.fr

### ISSUE THREAD

**Issue by patchint** [hnhx/librex#203]
Hi,

I want to add search.spaceint.fr to the instances list : 

Address : https://search.spaceint.fr/
Country : France

Yes the IP address shows Germany but it's only a reverse proxy to my server host in Marseille (it's the same for my ArchLinux mirror and every services we host like Mastodon etc etc)

**Comment by hnhx** [comment]
Make a PR please and I will merge it. Also despite it being a reverse proxy, use germany for the country.

**Comment by hnhx** [comment]
Okay I added it myself, no need to make PR
