### ISSUE TITLE
There's an issue when you add LibreX to custom search engine on every web browsers

### ISSUE THREAD

**Issue by patchint** [hnhx/librex#204]
On Firefox I can add it to my search engine but I can't change it to the correct address
![image](https://user-images.githubusercontent.com/55617813/230710987-414f079c-6dde-4b0f-a5d6-50a9bef25af4.png)

I think Firefox added the wrong address :/
![image](https://user-images.githubusercontent.com/55617813/230711020-5d6bab37-4f93-467c-9a86-e31b938e6080.png)

On edge I can change it (And I think it's the same on Chrome etc, but I mainly use Firefox)
![image](https://user-images.githubusercontent.com/55617813/230711044-1883b29a-67ea-44f7-893b-5a8001d7fdab.png)

So, what's wrong with it ? Is it my NGINX configuration or LibreX ?

NGINX
```
server {
...... # a lot of basic config...
	set $upstream librex:8080;

	location / {
		proxy_pass http://$upstream;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
}
...... # a lot of basic config...
```

**Comment by hnhx** [comment]
Seems like the hosters didn't follow the [hosting instructions](https://github.com/hnhx/librex/wiki/How-to-host-LibreX)...

You have to make it so opensearch.xml points to your domain.
