### ISSUE TITLE
Add a .onion

### ISSUE THREAD

**Issue by patchint** [hnhx/librex#207]
Hi,

I opened a Tor access for my LibreX (search.spaceint.fr)

Here's the address : http://pzmyxvp2l6nwmsl3qfhlze3dn3g5c5ovzoy5er6mce3uncbewny2tgad.onion/

![image](https://user-images.githubusercontent.com/55617813/230855297-a475663d-5c7e-40d8-9461-c98685c894b0.png)

**Comment by patchint** [comment]
Update :  I changed my VPS, now every IP addresses are located in France
141.95.158.57
2001:41d0:304:200::8096

**Comment by codedipper** [comment]
Fix your onion and I'll add it for you.

![pic-window-230520-1535-27](https://github.com/hnhx/librex/assets/59625582/b9b4cb9b-d14d-4e8f-a41f-45638657e716)

**Comment by patchint** [comment]
ahhh thanks I forgot it ! i'm going to make it

**Comment by patchint** [comment]
I put it back in place it's good!

new address : http://6d4nqt2rndvmhogpwrbqfvj2ur6e6nm2r6dzi7ny4wj6ai3j5hnvbhyd.onion/
![image](https://github.com/hnhx/librex/assets/55617813/cb87c9fa-10ff-4d66-97f6-76ed86127ffb)

**Comment by codedipper** [comment]
[f3b9bad](https://github.com/hnhx/librex/pull/229/commits/f3b9badfbc04a0aecd87c03ae572b9bd2d017b23)
