### ISSUE TITLE
Goodreads privacy frontend

### ISSUE THREAD

**Issue by mizzunet** [hnhx/librex#211]
Please add Goodreads privacy frontend, BilbiloReads
https://github.com/nesaku/BiblioReads

Thanks :)

**Comment by codedipper** [comment]
URLs are compatible, easy to implement. I'll work on it at some point.

**Comment by codedipper** [comment]
Implemented in #210, tested on [my LibreX onion instance](http://librex.revvybrr6pvbx4n3j4475h4ghw4elqr4t5xo2vtd3gfpu2nrsnhh57id.onion/) on bare PHP without Docker.
