### ISSUE TITLE
Image search does not work

### ISSUE THREAD

**Issue by Kaoplo** [hnhx/librex#216]
I launched my own LibreX instance and when I search for images, nothing comes up.
My instance can be accessed here: https://search.pawz.hu

**Comment by hnhx** [comment]
I'm not really sure why, I have tested other instances and the image search works fine there.
Maybe qwant rate limited your VPS?

**Comment by Kaoplo** [comment]
I'm running this instance locally, I have the same issue accessing it using a local IP address.

**Comment by Kaoplo** [comment]
Whoops didn't mean to close it

**Comment by hnhx** [comment]
Can you try doing an image search on qwant.com using a regular browser? Maybe your IP is blocked for some reason

**Comment by 305a385** [comment]
Are you using docker?
Have you tried updating librex?
Are you sure you installed all the right dependencies?
What operating system are you using?

**Comment by Kame03** [comment]
I remember ages ago I solved this by installing a couple of PHP libraries it was either something for scraping data or processing images, I cannot remember exactly, if someone know what LibreX depends on we can try that and it should solve the issue.

**Comment by Kame03** [comment]
I think the fix is installing these two:
`php-dom`
`php-curl`
