### ISSUE TITLE
librex.me is broken for me

### ISSUE THREAD

**Issue by CaptainFrosty** [hnhx/librex#223]
Only the Wikipedia box comes up. Wanted to verify this with someone else.

**Comment by codedipper** [comment]
Not a LibreX issue, the instance is getting rate limited.
I tried proxying through Tor and restarting Tor every 3 minutes to get a circuit faster, but there are just so many requests and they're impossible to handle (I counted 7,000+ searches in 12 hours a few days ago).

Would be nice to make rate limiting a little bit more clear to the user though.
