### ISSUE TITLE
[Feature Request] Add DuckDuckGo as an upstream search engine

### ISSUE THREAD

**Issue by 305a385** [hnhx/librex#232]
I noticed that there aren't many upstream search engines. In fact the only search engine for text search is google! ([if I read this source code right](https://github.com/hnhx/librex/tree/main/engines))

### Pros:
-  [Google ratelimits VPSs.](https://github.com/hnhx/librex/issues/226#issuecomment-1555097517) which can lead to issues such as text not showing (see #226); a second option for text searches could help workaround this
- More search engines = more results :), this is pretty self explanatory
- If you have your tinfoil hat on real tight, you could remove google as an upstream and still get text results

### Info that might help with implementation:
[Duckduckgo has an API but it only works for text](https://stackoverflow.com/a/38964931)

**Comment by hnhx** [comment]
From my experience DDG has horrible text results so thats why i didnt bother with it. I might implement in support for it as a fallback when Google blocks an instance though.
