### ISSUE TITLE
Long/Complex search queries gives no result/blank output.

### ISSUE THREAD

**Issue by vdbhb59** [hnhx/librex#239]
![image](https://github.com/hnhx/librex/assets/60728004/d0522b9b-48d8-419b-8cc5-083ec8e74b40)

As seen in the above snapshot, for example, if I try to find a error "composer requires php 8.0.2 and you are using php 7.4.3 error", the result is no output. This is for almost every other type of error.

But if I rerun this query after lets say 4-5 minutes, it brings up the search result.

Not sure if this is a bug or a rate limit/API issue?

Did not find such kind of issue in the list and I have been facing this for almost 4-5 days now, so raised here.

**Comment by codedipper** [comment]
~~I want to burn Google HQ.~~ It's probably a rate limit because the exact query works on my instance (fully updated).

**Comment by vdbhb59** [comment]
Yup, looks like it. Maybe I can keep a tab on logs to see if anything pops up.

**Comment by vdbhb59** [comment]
Still happening no matter what. Is there any workaround?
