### ISSUE TITLE
Quotation mark breaks sub-searches

### ISSUE THREAD

**Issue by icaroscherma** [hnhx/librex#249]
Using LibreX to search on **Google** `!g` , **Wikipedia** `!wiki`, etc for something specific (mandatorily including the word/sentence) , in other words, you must use double quotation mark `"` , it won't pass anything after the 1st quotation mark.

Example:
![image](https://github.com/hnhx/librex/assets/42467/b4a5ba6b-2d87-4900-9c25-2adf330b2acc)

Becomes:
![image](https://github.com/hnhx/librex/assets/42467/e3fca618-2d88-4525-97f6-08ce03ecf867)

I believe it's an encoding issue, as if I pass it encoded (example below):
![image](https://github.com/hnhx/librex/assets/42467/e018a04f-9b0f-4421-981a-4cba8bca6d3d)

It works:
![image](https://github.com/hnhx/librex/assets/42467/6a87171d-f2ad-4f2c-836b-41739feb4623)

**Comment by Ahwxorg** [comment]
This has been fixed in [LibreY](https://github.com/Ahwxorg/LibreY). LibreY is a fork of LibreX that aims to continue development on the project.

**Comment by icaroscherma** [comment]
Forgot to take some action here but I started using libre-y when @codedipper told me straight on my PR, thx guys.
