### ISSUE TITLE
random instance

### ISSUE THREAD

**Issue by person1030** [hnhx/librex#26]
Hello, it would be nice if he randomly changed instances, and not by hand

**Comment by Junosocks** [comment]
like everytime you open LibreX it would choose a random instance in the readme?

**Comment by hnhx** [comment]
Could you elaborate?

**Comment by WitherCubes** [comment]
@person1030 is telling to add all instances of libreX to [farside](https://github.com/benbusby/farside) and randomly change instances.

**Comment by hnhx** [comment]
Well thats not my project so I can't really do anything about it.
