### ISSUE TITLE
Feature Request: Search Bangs

### ISSUE THREAD

**Issue by WitherCubes** [hnhx/librex#28]
Feature Request: Implementing DuckDuckGo-style search bangs. For example [whoogle](https://github.com/benbusby/whoogle-search/blob/main/app/utils/bangs.py) does implement it.

I do not know if it is possible to implement it but it would be a good feature.

**Comment by hnhx** [comment]
Done, thanks for the idea.

https://github.com/hnhx/librex/commit/c847b0c874359598a53bdf3fe120242ebc3350a0
