### ISSUE TITLE
Add librex.catalyst.sx to instance list

### ISSUE THREAD

**Issue by Vardorien** [hnhx/librex#29]
I'd like for my instance to be added to the list.

URL: [https://librex.catalyst.sx/](https://librex.catalyst.sx/)
Country: US 🇺🇸

**Comment by hnhx** [comment]
Added it, thanks for hosting LibreX.

**Comment by hnhx** [comment]
@Vardorien hey I removed your instance because it contains JS and its behind cloudflare, if you get rid of the JS and the cloudflare protection I will add back your instance.

**Comment by Vardorien** [comment]
> @Vardorien hey I removed your instance because it contains JS and its behind cloudflare, if you get rid of the JS and the cloudflare protection I will add back your instance.

The JS is probably from Cloudflare. Let me

**Comment by Vardorien** [comment]
Cloudflare protection, and the JavaScript have both been removed.
