### ISSUE TITLE
Mozilla Firefox Addon

### ISSUE THREAD

**Issue by Erghel** [hnhx/librex#31]
I made and released a simple Addon for Firefox that will install LibreX (on domain - ``https://librex.beparanoid.de/`` ) as the primary search engine.

Source code - [**here**](https://github.com/Erghel/LibreX-Extension)
Addon store page - https://addons.mozilla.org/en-US/firefox/addon/librex-privacy-search/

If it is possible to add a mention of this addon in the README, I would be very happy.

**Comment by hnhx** [comment]
Hey thats very nice of you however, there is no need for an addon to do this since we have opensearch.xml.
If you go to settings in Firefox, then click on "Search" and change it to "Add search bar in toolbar" the next time you visit https://librex.beparanoid.de/ you will see a little "+" on the mini search bar that will let you add LibreX as a search engine.

If you would modify this extension and make it so it uses a random LibreX instance on every search I will be glad to add it.

**Comment by Erghel** [comment]
Ok! I will try do it. 
Thank you for answer!

**Comment by Terkyz** [comment]
> Hey thats very nice of you however, there is no need for an addon to do this since we have opensearch.xml. If you go to settings in Firefox, then click on "Search" and change it to "Add search bar in toolbar" the next time you visit https://librex.beparanoid.de/ you will see a little "+" on the mini search bar that will let you add LibreX as a search engine.
> 
> If you would modify this extension and make it so it uses a random LibreX instance on every search I will be glad to add it.

This is not possible in Firefox Android, directly to add a search engine it is necessary for the URL to use `/search?q=%s` that LibreX does not have, there is a way to fix this?

**Comment by Erghel** [comment]
> > Hey thats very nice of you however, there is no need for an addon to do this since we have opensearch.xml. If you go to settings in Firefox, then click on "Search" and change it to "Add search bar in toolbar" the next time you visit https://librex.beparanoid.de/ you will see a little "+" on the mini search bar that will let you add LibreX as a search engine.
> 
> > 
> 
> > If you would modify this extension and make it so it uses a random LibreX instance on every search I will be glad to add it.
> 
> 
> 
> This is not possible in Firefox Android, directly to add a search engine it is necessary for the URL to use `/search?q=%s` that LibreX does not have, there is a way to fix this?

https://librex.beparanoid.de/search.php?q=%s

Use this
