### ISSUE TITLE
Wikipedia instead of wikiless in special query

### ISSUE THREAD

**Issue by E8LL4IQuU** [hnhx/librex#33]
Search "Hubby" return special query linking to wikipedia (not wikiless) as first result

![librex hubby search](https://user-images.githubusercontent.com/109896400/180639494-57ccb9c9-9cdc-45e0-8b7b-59db03ca79a8.PNG)

**Comment by hnhx** [comment]
Did you set a wikiless instance in the settings?

Works fine on my instance: https://librex.beparanoid.de/search.php?q=hubby

**Comment by E8LL4IQuU** [comment]
I am using last tor instance in instance list because beparanoid tor instance is unreachable for me with error 0xF0. Setting up instances fixed the problem
