### ISSUE TITLE
Whoogle comparison

### ISSUE THREAD

**Issue by benbusby** [hnhx/librex#35]
Hi! I just came across your project while adding support for it in Farside (as requested in https://github.com/benbusby/farside/issues/47).

I was looking through the README and noticed that the comparison to Whoogle indicates that Whoogle doesn't support "Privacy frontend redirect", which isn't quite true (unless I'm misunderstanding your definition). Whoogle does support redirecting to privacy frontends for Twitter->Nitter, Youtube->Invidious/Piped, Reddit->Libreddit/Teddit, and quite a few others via user-level configuration.

Just wanted to point that out. If you have an issue with how Whoogle implemented that feature though, let me know. Really like your project btw!

**Comment by hnhx** [comment]
Updated it, thanks.
