### ISSUE TITLE
Horizontal scrollbars appearing in image search on small screens 

### ISSUE THREAD

**Issue by martin-desktops** [hnhx/librex#38]
Librex doesn't scale images results what on small size devices/windows forces uncomforable navigation with scrollbars.

**Possible solution:**
Scale images to match screen size on small screens.

![Screenshot from 2022-08-07 19-06-32](https://user-images.githubusercontent.com/64419373/183302882-728ffee5-e42a-4f67-892a-0e4f1f334e09.png)

Regards, Martin

**Comment by hnhx** [comment]
fixed it, thanks
