### ISSUE TITLE
[Bug] iOS shows blank page upon pressing image result

### ISSUE THREAD

**Issue by Mennaruuk** [hnhx/librex#4]
Hi! Got to learn about LibreX today, and I love it.

I was using it on my iPhone X, and when I pressed one of the image results to zoom into it, iOS kept showing me a blank page. I looked it up, and it appears that since 2020, iOS "[no longer allows pages to perform top-level meta redirects to data URLs.](https://developer.apple.com/forums/thread/650034?answerId=624675022#624675022)" However, "a direct navigation to a dataURL." I'm not sure what's the difference between top-level meta redirects vs. direct navigation.

**Comment by hnhx** [comment]
Hi! This is not an iOS issue but rather an issue with safari.
For some reason safari doesn't allow for base64 encoded images to be displayed.
The reason why the images are in base64 format is to prevent clients from connecting to Google servers.
