### ISSUE TITLE
OCSP error

### ISSUE THREAD

**Issue by E8LL4IQuU** [hnhx/librex#50]
Can someone confirm that there's a problem connecting to beparanoid services with Librewolf with enforced OCSP hard-fail.

I'm getting SEC_ERROR_OCSP_SERVER_ERROR when trying to connect to yt.beparanoid.de, beparanoid.de or others.

I have no vpn enabled, which usually causes this error

edit: funami.tech and catalyst.sx instances seem to be loading fine

**Comment by hnhx** [comment]
Works fine for me.
