### ISSUE TITLE
My instance doesn't show Google results (not a problem with LibreX but maybe you can help)

### ISSUE THREAD

**Issue by Ahwxx** [hnhx/librex#52]
Hey there,

My instance: [https://search.ahwx.org](https://search.ahwx.org/) doesn't show results. Is this a problem with my firewall? I haven't changed anything in my DNS and Cloudflare proxy settings.

Thanks!

**Comment by hnhx** [comment]
It seems to be working now.

Do you want me to add your instance to the list?

**Comment by Extravi** [comment]
It seems to be working.

**Comment by Extravi** [comment]
bruh the main site is a rick roll

**Comment by Ahwxx** [comment]
Yeah, it's working now. I don't know what happened but I couldn't get any results for a good hour (more  than one hour) and google.com worked fine. Thanks!

PS: I changed the redirection rule, so now it's no longer a rick roll, but my actual website. Thanks!

**Comment by Extravi** [comment]
The same thing just happened to me it's caused from spamming the search and google will block you for a tiny bit.

**Comment by Ahwxx** [comment]
And Google.com works for you?

**Comment by Ahwxx** [comment]
PS I like your website @Extravi

**Comment by Extravi** [comment]
not anymore i ping it from my instance and got this http://fra16s42-in-x04.1e100.net/

**Comment by Extravi** [comment]
i have been blocked for less then an hour i will wait and see what happens

**Comment by Ahwxx** [comment]
Alright, I'll just deal with google being annoying then. Thanks for your help both!

**Comment by Extravi** [comment]
I am not sure when google will unblock my vps

**Comment by Extravi** [comment]
> PS I like your website @Extravi

thank you
