### ISSUE TITLE
API doesn't show 1337x links.

### ISSUE THREAD

**Issue by amogusussy** [hnhx/librex#54]
It will just return something along the lines of `/engines/bittorrent/get_magnet_1337x.php?url=https://1337x.to/torrent/{other info}` rather than a magnet link. It's only an issue with 1337x links.

**Comment by hnhx** [comment]
This is not a bug, 1337x doesn't show magnet links when you search for something, you have to click on each torrent to get the magnet link so thats why I made the get_magnet_1337x.php file to get the magnet link.

If you make a request to that it will return the 1337x magnet link.
