### ISSUE TITLE
Doesn't work sample text search after update

### ISSUE THREAD

**Issue by mad-reyk** [hnhx/librex#78]
https://search.madreyk.xyz
But the search for images, videos and torrents works. I find that the https://search.ahwx.org/ instance also didn't work as well. If I switch branch to the revert-6-main, everything is works, so I won't update just yet.

**Comment by Extravi** [comment]
no google just blocked you're instance for too many automated queries it happens sometimes

**Comment by Extravi** [comment]
curl google search to see the error when that happens

**Comment by Extravi** [comment]
you should be fine to update

**Comment by mad-reyk** [comment]
I already curled google, and there were no errors, but after the update, text search doesn't work again

**Comment by Extravi** [comment]
did it say anything about automated queries?

**Comment by Extravi** [comment]
because it works for me

**Comment by Extravi** [comment]
everything in librex is working

**Comment by Extravi** [comment]
maybe update you're config etc

**Comment by mad-reyk** [comment]
Ok, everything works after checkout, so it was probably google

**Comment by Extravi** [comment]
🙂
