### ISSUE TITLE
Redirection in the API

### ISSUE THREAD

**Issue by trueauracoral** [hnhx/librex#8]
I have been doing some scripting with the librex API. I want to be able to redirect youtube/twitter/reddit search results to privacy front-ends without having to write extra code myself to do the redirection. Could `&` operators be added to redirect to privacy frontends in the API? Possiby:
`.../api.php?q=youtube&p=2&type=0&youtuberedirect=invidio.xamh.de&twitterredirect=nitter.net&redditredirect=teddit.net`

**Comment by hnhx** [comment]
Hey! This is already a feature.
You can do it like this: 

`/api.php?q=youtube&p=2&type=0&invidious=https://invidio.xamh.de&nitter=https://nitter.net`

The best way to setup the query param is to go to settings, make the changes that you want and just copy paste the query param there and just use it with the API.
