### ISSUE TITLE
[Engine Support] RARBG

### ISSUE THREAD

**Issue by bachig26** [hnhx/librex#81]
Index Page: https://rarbg.to/index80.php | Search All Page: https://rarbg.to/torrents.php

Requesting support for the RARBG Torrent Engine

**Comment by Extravi** [comment]
why tho the current torrent index works just fine I can find anything in seconds

**Comment by bachig26** [comment]
> why tho the current torrent index works just fine I can find anything in seconds 

From my experience, I use mostly RARBG for torrent due to the result I look for is better and secondly 1337x. That's a reason I requested this.

If it's not added, it's okay...I just want to suggest it.

**Comment by Extravi** [comment]
alright

**Comment by hnhx** [comment]
Hey!

It seems like its impossible to search on this page without javascript so I can't really add it.
