### ISSUE TITLE
theme query parameter is stripped during navigation

### ISSUE THREAD

**Issue by nihil-admirari** [hnhx/librex#84]
I don't like to store cookies of any kind; thus selecting Light theme in Settings is not an option for me.

Theme can be selected though query parameter, e.g. `https://librex.beparanoid.de/search.php?q=librex&theme=light`, which doesn't rely on cookies.

Unfortunately, that query parameter is stripped away when going to the second page of search results, choosing to search for images etc.

**Comment by Extravi** [comment]
I don't see anything wrong with cookies

**Comment by nihil-admirari** [comment]
Parameter is already accepted by LibreX, it's simply not preserved during navigation. If no-one is going to fix it, well, close the issue. But don't you tell me that I should stop worrying and start to like your cookies.

**Comment by hnhx** [comment]
Done, now settings set via query parameters or via a post request persist.
