### ISSUE TITLE
[Feature request] Instant answers 

### ISSUE THREAD

**Issue by sioodmy** [hnhx/librex#86]
Hi, I really liked your search engine. However I think it lacks instant answers like google.
examples: 
![image](https://user-images.githubusercontent.com/81568712/198873612-9b58147a-b698-4ac8-a424-2b68fc1d232c.png)
![image](https://user-images.githubusercontent.com/81568712/198873616-08509a7d-9d87-4d9e-8c5b-2ce29c1850d0.png)
![image](https://user-images.githubusercontent.com/81568712/198873627-4d53c9e7-b955-474a-b74f-688e8c21e57b.png)
![image](https://user-images.githubusercontent.com/81568712/198873639-d8b9459b-0386-4b62-b4d4-a4f97d0b318a.png)

**Comment by Extravi** [comment]
atm I have a pull request for something kinda like that ![Screenshot_20221101-135824_DuckDuckGo.jpg](https://user-images.githubusercontent.com/98912029/199304651-9a930d02-f961-49ee-89a2-1d25f0b688fc.jpg)

**Comment by Extravi** [comment]
https://github.com/hnhx/librex/pull/77

**Comment by hnhx** [comment]
There are already plenty of them:
- weather
- whats my ip
- whats my user agent
- 2450.63 usd to eur
...

Ofc more will be added in the future.
