### ISSUE TITLE
Add more alternative frontends

### ISSUE THREAD

**Issue by cecxl** [hnhx/librex#87]
quetre and libremdb support would be great.

**Comment by Extravi** [comment]
https://github.com/hnhx/librex/issues/79

**Comment by Extravi** [comment]
I don't think that is the main focus atm

**Comment by cecxl** [comment]
> #79

I don't mean adding support to more search engines like google and brave, I mean the redirection of youtube to invidious kind of thing. the 'Privacy friendly frontends' setting.

**Comment by Extravi** [comment]
oh okay sorry

**Comment by hnhx** [comment]
In the next commit I will make it a feature so you can add your custom redirects.
