### ISSUE TITLE
Librex only shows one result per site.

### ISSUE THREAD

**Issue by amogusussy** [hnhx/librex#93]
For an example, this is the result if you search `how to join two strings in python stackoverflow` in google:

[Google image](https://imgur.com/VfKv8pX)

And this is the result if you search the same thing in librex:

[Librex image](https://imgur.com/9ahmLBS)

There's no extra link below the main one.

**Comment by vars1ty** [comment]
Had it happen for me when it was hosted on `localhost`, then it vanished when I put it on my server.
Although it no longer happens on my fork, forgot what I changed to fix it tbh.

**Comment by Extravi** [comment]
never had that happen to me on localhost
